### ISSUE TITLE
Roadmap 🚀

### ISSUE THREAD

**Issue by sjockers** [datenguide/datenguide#1]
(draft, to be refined)

Short term:

## 1. Technical stack

Upgrade [datenguide-frontend](https://github.com/datenguide/datenguide-frontend) to Gatsby v2 and the most recent version of other core dependencies. Improve technical documentation of both [datenguide-frontend](https://github.com/datenguide/datenguide-frontend) and [datenguide-backend](https://github.com/datenguide/datenguide-backend) to make it easier to contribute to the project.

- [x] [Upgrade Gatsby](https://github.com/datenguide/datenguide-frontend/issues/26)
- [x] [Upgrade Datenguide API](https://github.com/datenguide/datenguide-frontend/issues/27)
- [x] [Upgrade material design](https://github.com/datenguide/datenguide-frontend/issues/28)
- [x] [Upgrade README.md for datenguide-frontend](https://github.com/datenguide/datenguide-frontend/issues/29)
- [x] [Upgrade README.md for datenguide-backend](https://github.com/datenguide/datenguide-backend/issues/15)
- [x] [Consolidate api.genesapi.org and api.datengui.de](https://github.com/datenguide/datenguide-backend/issues/16)

## [2. Regional and local pages (mid-december)](https://github.com/datenguide/datenguide/milestone/1)

Usable prototype focusing on regional detail pages for each federal state and district (nuts levels 1 & 3)

## [3. Topical pages (end-December)](https://github.com/datenguide/datenguide/milestone/2)

Refined prototype that includes both regional (e.g. states, districts, cities) and topical detail pages (e.g. environment, health, education)

---

Mid term:

## 4. Documentation and case study (early 2019)

Explain how datenguide works and publish at least one practical example

## 5. Hackdays (early to mid 2019)

Organize public hackdays around official statistics in at least two German cities
